steps:

# Checkout origin master for "Nx Affected" commands
#  - name: git
#    args: [git fetch --no-tags --prune --depth=5 origin master]

# Install dependencies
  - name: node
    entrypoint: yarn
    args: [install --frozen-lockfile]
    id: deps

# Check formatting
  - name: node
    entrypoint: yarn
    args: [ci:format]
    waitFor: [deps]


# Lint
  - name: node
    entrypoint: yarn
    args: [yarn ci:lint]
    waitFor: [deps]
