steps:

# Checkout origin master for "Nx Affected" commands
#  - name: git
#    args: [fetch --no-tags --prune --depth=5 origin master]


  - name: gcr.io/cloud-builders/git
    entrypoint: bash
    args: ['-c', 'git fetch --no-tags --prune --depth=5 origin master']

# Install dependencies
  - name: node
    entrypoint: bash
    args: ['-c', 'yarn install --frozen-lockfile']
    id: deps
    waitFor: [-]

# Check formatting
  - name: node
    entrypoint: bash
    args: ['-c', 'yarn ci:format']
    waitFor: [deps]


# Lint
  - name: node
    entrypoint: bash
    args: ['-c', 'yarn ci:lint']
    waitFor: [deps]
