steps:

# Checkout origin master for "Nx Affected" commands
#  - id: fetch_master
#    name: node
#    entrypoint: bash
#    args: ['-c', 'git fetch --no-tags --prune --depth=5 origin master']
  - id: fetch_master
    name: node
    entrypoint: bash
    args:
      - -c
      - |-
      # get the .git directory only
      git clone --branch $BRANCH_NAME git@github.com:<USER_NAME>/$REPO_NAME /tmp/repo ;
      # move it to the workspace
      mv /tmp/repo/.git .

# Install dependencies
  - id: install_deps
    name: node
    entrypoint: bash
    args: ['-c', 'yarn install --frozen-lockfile']


# Check formatting
  - id: ci_format
    name: node
    entrypoint: bash
    args: ['-c', 'yarn ci:format']
    waitFor: [install_deps]


# Lint
  - id: ci_lint
    name: node
    entrypoint: bash
    args: ['-c', 'yarn ci:lint']
    waitFor: [install_deps]
