version: '3.9'

services:
  base:
    restart: always
    build:
      context: .
      dockerfile: docker/base.dockerfile
    volumes:
      - ./:/app # Mount the entire monorepo directory
      - node-modules:/app/node_modules # Share node_modules between containers
    platform: linux/amd64
