export enum AuthStage {
  initialization = 'initialization',
  enteringEmail = 'enteringEmail',
  fetchingProviders = 'fetchingProviders',
  choosingProvider = 'choosingProvider',
  authenticatingAnonymously = 'authenticatingAnonymously',
  authenticatingWithGoogle = 'authenticatingWithGoogle',
  authenticatingWithGitHub = 'authenticatingWithGitHub',
  authenticatingWithEmailAndPassword = 'authenticatingWithEmailAndPassword',
  authenticatingWithPhoneNumber = 'authenticatingWithPhoneNumber',
  authenticatingWithEmailLink = 'authenticatingWithEmailLink',
  restoringPassword = 'restoringPassword',
  signingOut = 'signingOut',
  signedIn = 'signedIn',
}
