import { User } from '@prisma/client';

export const mockUsers: User[] = [
  {
    id: '123456',
    userName: 'JohnDoe',
    role: 'USER',
    firstName: 'John',
    lastName: 'Doe',
    photoURL: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    isPushNotificationsEnabled: false,
    lastTimeSignedIn: new Date(),
  },
  {
    id: '456123',
    userName: 'JaneDoe',
    role: 'USER',
    firstName: 'Jane',
    lastName: 'Doe',
    photoURL: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    isPushNotificationsEnabled: false,
    lastTimeSignedIn: new Date(),
  },
  {
    id: '456123',
    userName: 'Jack',
    role: 'USER',
    firstName: 'Jack',
    lastName: 'Smith',
    photoURL: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    isPushNotificationsEnabled: true,
    lastTimeSignedIn: new Date(),
  },
];
